version: "3"
services:
  web:
    image: httpd:2.4
    container_name: "web"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apache/conf:/usr/local/apache2/conf
    links:
      - app1
  app1:
    image: my-tomcat-jib:latest
    container_name: "app1"
    ports:
      - 8080:8080
    environment:
      - APP_NAME=app1


