version: "3"
services:
  web:
    image: httpd:2.4
    container_name: "web"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apache/conf:/usr/local/apache2/conf
      - ./apache/htdocs:/usr/local/apache2/htdocs
    links:
      - app1
      - app2
  app1:
    image: my-tomcat-jib:latest
    container_name: "app1"
    ports:
      - 8081:8080
    environment:
      - APP_NAME=app1
  app2:
    image: my-tomcat-jib:latest
    container_name: "app2"
    ports:
      - 8082:8080
    environment:
      - APP_NAME=app2
